version: "3"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app-container
    environment:
      FLASK_ENV: development
      FLASK_APP: app/__init__.py
    ports:
      - "5000:5000"
  mysql:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    networks:
      - mynetwork
networks:
  mynetwork:

